include: package:very_good_analysis/analysis_options.3.0.0.yaml

analyzer:
  exclude:
    - build/**
    - "**/generated_plugin_registrant.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/i18n/messages*.dart"
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore

linter:
  rules:
    public_member_api_docs: false
